### PR TITLE
py2/py3 compatibility for testing purposes

### PR DESCRIPTION
**Pull request by klintan**
Trying to import it for testing in a shared repo of py3 code but it's not working. I think these changes will fix it.

*Issue #, if available:*
Py2/Py3 compatbility

*Description of changes:*
Updated for compatibility

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by villasv** [comment]
The AWS Glue library for Spark Jobs only supports Python 2.7. I'm afraid of merging code changes not coming from the official repository, because I wish this library wouldn't diverge from the original one apart from the `setup.py` that allows local installation.

In fact, I should have specified that using [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)...

**Comment by villasv** [comment]
Maybe you could convince the original maintainers at AWSLabs to merge your changes? :-/

**Comment by klintan** [comment]
> The AWS Glue library for Spark Jobs only supports Python 2.7. I'm afraid of merging code changes not coming from the official repository, because I wish this library wouldn't diverge from the original one apart from the `setup.py` that allows local installation.
> 
> In fact, I should have specified that using [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)...

Yeah no worries, was more of a symbolic PR, to hear your thoughts. As I said we have a shared library and everything else is Py3 so just wanted to import and test which wouldn't work without some work on the compatibility.

**Comment by klintan** [comment]
> Maybe you could convince the original maintainers at AWSLabs to merge your changes? :-/

Put in a PR, https://github.com/awslabs/aws-glue-libs/pull/23 doubt they'll merge, but I'll close this one regardless.

**Pull request closed without merging**
